---
version: "3.7"

name: carbon_joint_web_components
services:
  gateway:
    image: nginx:stable-alpine
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "2525:443"
    volumes:
      - ./container/conf:/etc/nginx
      - ./container/certs:/etc/nginx/certs
      - ./storybook-static:/usr/share/nginx/html
